---
services:
  plantuml:
    env_file: .env.plantuml
    image: registry.pub.deployment.center/asset/plantuml:${SWARMIT_IMAGES_IMAGE_TAG}
    labels:
      - com.swarmit.version=0.1
      - com.swarmit.project=otcbox
      - com.swarmit.asset=otcbox_intern_docu_plantuml
      - com.swarmit.feature.images.enabled=True
      - com.swarmit.images.version=alpha-0.1
      - com.swarmit.feature.core.enabled=True
      - com.swarmit.core.version=alpha-0.1
      - com.swarmit.feature.ingress.enabled=True
      - com.swarmit.ingress.version=alpha-0.1
      - com.swarmit.asset.isPublic=True
      - traefik.constraint-label=traefik-public
      - traefik.http.services.otcbox_intern_docu_plantuml.loadbalancer.server.port=8080
      - traefik.http.routers.otcbox_intern_docu_plantuml.tls=true
      - traefik.http.routers.otcbox_intern_docu_plantuml.entrypoints=web-secure
      - traefik.http.routers.otcbox_intern_docu_plantuml.middlewares=frameHeader@file,ingress-errors@file
      - traefik.http.routers.otcbox_intern_docu_plantuml.rule=Host(`plantuml.${SWARMIT_INGRESS_BASE_DOMAIN}`)
    deploy:
      endpoint_mode: dnsrr
    healthcheck:
      test: curl http://localhost:8080 > /dev/null 2>&1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      INFRA_INGRESS_DOMAIN: ".${SWARMIT_INGRESS_BASE_DOMAIN}"
      INFRA_INGRESS_URL: "https://${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_DOMAIN: "plantuml.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_URL: "https://plantuml.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_BOX: "intern"
      SWARMIT_CORE_ENABLED: "[]"
      SWARMIT_IMAGES_ENABLED: "[]"
      SWARMIT_IMAGES_IMAGE_TAG: "${SWARMIT_IMAGES_IMAGE_TAG}"
      SWARMIT_IMAGES_REGISTRY_DOMAIN: "${SWARMIT_IMAGES_REGISTRY_DOMAIN}"
      SWARMIT_IMAGES_REGISTRY_URL: "${SWARMIT_IMAGES_REGISTRY_URL}"
      SWARMIT_INFRA: "${SWARMIT_INFRA}"
      SWARMIT_INFRA_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_ASSET_DOMAIN: "True"
      SWARMIT_INGRESS_BASE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_BOX_DOMAIN: "True"
      SWARMIT_INGRESS_DASHBOARD: "True"
      SWARMIT_INGRESS_ERROR_PAGES: "True"
      SWARMIT_INGRESS_INFRA_DOMAIN: "True"
      SWARMIT_INGRESS_LE_CHALLENGE_TYPE: "unset"
      SWARMIT_INGRESS_LE_DNS_CHALLENGE_DELAY: "5"
      SWARMIT_INGRESS_LE_DNS_ENV_NAME: ""
      SWARMIT_INGRESS_LE_DNS_KEY: "secret"
      SWARMIT_INGRESS_LE_DNS_PROVIDER: ""
      SWARMIT_INGRESS_LE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_EMAIL: "mail@${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_ENABLE: "False"
      SWARMIT_INGRESS_LOG_LEVEL: "ERROR"
      SWARMIT_INGRESS_MAIL_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_PORT: "443"
      SWARMIT_INGRESS_PROTOCOL: "https://"
      SWARMIT_INGRESS_REPORTS: "True"
      SWARMIT_INGRESS_SERVICE_DOMAIN: "True"
      SWARMIT_INGRESS_SKIP_SSL_VERIFY: "${SWARMIT_INGRESS_SKIP_SSL_VERIFY}"
      SWARMIT_INGRESS_STACK_DOMAIN: "True"
      SWARMIT_LOGOHOST: "${SWARMIT_LOGOHOST}"
      SWARMIT_PATH: "/app/swarmit/"
      SWARMIT_PROVIDER: "swarm"
      SWARMIT_SERVICE: "plantuml"
      SWARMIT_SERVICE_DOMAIN: "plantuml.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_STACK: "docu"
      SWARMIT_VOLUMES_PATH: "${VOLUMES_FOLDER}"
    networks:
      otcbox_intern_svcs:
      otcbox_public:
    volumes:
      - ${VOLUMES_FOLDER}/volumes/otcbox/swarmit/hooks:/var/lib/swarmit/hooks
      - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 40m
        max-file: 2
        mode: non-blocking
        max-buffer-size: 4m
  mermaid:
    env_file: .env.mermaid
    image: registry.pub.deployment.center/asset/mermaid:${SWARMIT_IMAGES_IMAGE_TAG}
    labels:
      - com.swarmit.version=0.1
      - com.swarmit.project=otcbox
      - com.swarmit.asset=otcbox_intern_docu_mermaid
      - com.swarmit.feature.images.enabled=True
      - com.swarmit.images.version=alpha-0.1
      - com.swarmit.feature.core.enabled=True
      - com.swarmit.core.version=alpha-0.1
      - com.swarmit.feature.ingress.enabled=True
      - com.swarmit.ingress.version=alpha-0.1
      - com.swarmit.asset.isPublic=True
      - traefik.constraint-label=traefik-public
      - traefik.http.services.otcbox_intern_docu_mermaid.loadbalancer.server.port=8080
      - traefik.http.routers.otcbox_intern_docu_mermaid.tls=true
      - traefik.http.routers.otcbox_intern_docu_mermaid.entrypoints=web-secure
      - traefik.http.routers.otcbox_intern_docu_mermaid.middlewares=frameHeader@file,ingress-errors@file
      - traefik.http.routers.otcbox_intern_docu_mermaid.rule=Host(`mermaid.${SWARMIT_INGRESS_BASE_DOMAIN}`)
    deploy:
      endpoint_mode: dnsrr
    healthcheck:
      test: ["CMD", "/healthcheck", "-tcp", "127.0.0.1:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      INFRA_INGRESS_DOMAIN: ".${SWARMIT_INGRESS_BASE_DOMAIN}"
      INFRA_INGRESS_URL: "https://${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_DOMAIN: "mermaid.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_URL: "https://mermaid.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_BOX: "intern"
      SWARMIT_CORE_ENABLED: "[]"
      SWARMIT_IMAGES_ENABLED: "[]"
      SWARMIT_IMAGES_IMAGE_TAG: "${SWARMIT_IMAGES_IMAGE_TAG}"
      SWARMIT_IMAGES_REGISTRY_DOMAIN: "${SWARMIT_IMAGES_REGISTRY_DOMAIN}"
      SWARMIT_IMAGES_REGISTRY_URL: "${SWARMIT_IMAGES_REGISTRY_URL}"
      SWARMIT_INFRA: "${SWARMIT_INFRA}"
      SWARMIT_INFRA_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_ASSET_DOMAIN: "True"
      SWARMIT_INGRESS_BASE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_BOX_DOMAIN: "True"
      SWARMIT_INGRESS_DASHBOARD: "True"
      SWARMIT_INGRESS_ERROR_PAGES: "True"
      SWARMIT_INGRESS_INFRA_DOMAIN: "True"
      SWARMIT_INGRESS_LE_CHALLENGE_TYPE: "unset"
      SWARMIT_INGRESS_LE_DNS_CHALLENGE_DELAY: "5"
      SWARMIT_INGRESS_LE_DNS_ENV_NAME: ""
      SWARMIT_INGRESS_LE_DNS_KEY: "secret"
      SWARMIT_INGRESS_LE_DNS_PROVIDER: ""
      SWARMIT_INGRESS_LE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_EMAIL: "mail@${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_ENABLE: "False"
      SWARMIT_INGRESS_LOG_LEVEL: "ERROR"
      SWARMIT_INGRESS_MAIL_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_PORT: "443"
      SWARMIT_INGRESS_PROTOCOL: "https://"
      SWARMIT_INGRESS_REPORTS: "True"
      SWARMIT_INGRESS_SERVICE_DOMAIN: "True"
      SWARMIT_INGRESS_SKIP_SSL_VERIFY: "${SWARMIT_INGRESS_SKIP_SSL_VERIFY}"
      SWARMIT_INGRESS_STACK_DOMAIN: "True"
      SWARMIT_LOGOHOST: "${SWARMIT_LOGOHOST}"
      SWARMIT_PATH: "/app/swarmit/"
      SWARMIT_PROVIDER: "swarm"
      SWARMIT_SERVICE: "mermaid"
      SWARMIT_SERVICE_DOMAIN: "mermaid.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_STACK: "docu"
      SWARMIT_VOLUMES_PATH: "${VOLUMES_FOLDER}"
    networks:
      otcbox_intern_svcs:
      otcbox_public:
    volumes:
      - ${VOLUMES_FOLDER}/volumes/otcbox/swarmit/hooks:/var/lib/swarmit/hooks
      - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 40m
        max-file: 2
        mode: non-blocking
        max-buffer-size: 4m
networks:
  otcbox_intern_svcs:
    external: true
  otcbox_public:
    external: true