---
services:
  logs:
    env_file: .env.logs
    image: registry.pub.deployment.center/asset/dozzle:${SWARMIT_IMAGES_IMAGE_TAG}
    labels:
      - com.swarmit.version=0.1
      - com.swarmit.project=otcbox
      - com.swarmit.asset=otcbox_swarmit_core_logs
      - com.swarmit.feature.images.enabled=True
      - com.swarmit.images.version=alpha-0.1
      - com.swarmit.feature.core.enabled=True
      - com.swarmit.core.version=alpha-0.1
      - com.swarmit.feature.ingress.enabled=True
      - com.swarmit.ingress.version=alpha-0.1
      - com.swarmit.asset.isPublic=True
      - traefik.constraint-label=traefik-public
      - traefik.http.services.otcbox_swarmit_core_logs.loadbalancer.server.port=8080
      - traefik.http.routers.otcbox_swarmit_core_logs.tls=true
      - traefik.http.routers.otcbox_swarmit_core_logs.entrypoints=web-secure
      - traefik.http.routers.otcbox_swarmit_core_logs.middlewares=ingress-errors@file
      - traefik.http.routers.otcbox_swarmit_core_logs.rule=Host(`logs.${SWARMIT_INGRESS_BASE_DOMAIN}`)
    deploy:
      endpoint_mode: dnsrr
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
        order: stop-first
      placement:
        constraints:
          - node.role == manager
    ports:
      - published: 8989
        target: 8080
        mode: host
    healthcheck:
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      INFRA_INGRESS_DOMAIN: ".${SWARMIT_INGRESS_BASE_DOMAIN}"
      INFRA_INGRESS_URL: "https://${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_DOMAIN: "logs.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SERVICE_INGRESS_URL: "https://logs.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_BOX: "swarmit"
      SWARMIT_CORE_ENABLED: "[]"
      SWARMIT_IMAGES_ENABLED: "[]"
      SWARMIT_IMAGES_IMAGE_TAG: "${SWARMIT_IMAGES_IMAGE_TAG}"
      SWARMIT_IMAGES_REGISTRY_DOMAIN: "${SWARMIT_IMAGES_REGISTRY_DOMAIN}"
      SWARMIT_IMAGES_REGISTRY_URL: "${SWARMIT_IMAGES_REGISTRY_URL}"
      SWARMIT_INFRA: "${SWARMIT_INFRA}"
      SWARMIT_INFRA_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_ASSET_DOMAIN: "True"
      SWARMIT_INGRESS_BASE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_BOX_DOMAIN: "True"
      SWARMIT_INGRESS_DASHBOARD: "True"
      SWARMIT_INGRESS_ERROR_PAGES: "True"
      SWARMIT_INGRESS_INFRA_DOMAIN: "True"
      SWARMIT_INGRESS_LE_CHALLENGE_TYPE: "unset"
      SWARMIT_INGRESS_LE_DNS_CHALLENGE_DELAY: "5"
      SWARMIT_INGRESS_LE_DNS_ENV_NAME: ""
      SWARMIT_INGRESS_LE_DNS_KEY: "secret"
      SWARMIT_INGRESS_LE_DNS_PROVIDER: ""
      SWARMIT_INGRESS_LE_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_EMAIL: "mail@${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_LE_ENABLE: "False"
      SWARMIT_INGRESS_LOG_LEVEL: "ERROR"
      SWARMIT_INGRESS_MAIL_DOMAIN: "${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_INGRESS_PORT: "443"
      SWARMIT_INGRESS_PROTOCOL: "https://"
      SWARMIT_INGRESS_REPORTS: "True"
      SWARMIT_INGRESS_SERVICE_DOMAIN: "True"
      SWARMIT_INGRESS_SKIP_SSL_VERIFY: "${SWARMIT_INGRESS_SKIP_SSL_VERIFY}"
      SWARMIT_INGRESS_STACK_DOMAIN: "True"
      SWARMIT_LOGOHOST: "${SWARMIT_LOGOHOST}"
      SWARMIT_PATH: "/app/swarmit/"
      SWARMIT_PROVIDER: "swarm"
      SWARMIT_SERVICE: "logs"
      SWARMIT_SERVICE_DOMAIN: "logs.${SWARMIT_INGRESS_BASE_DOMAIN}"
      SWARMIT_STACK: "core"
      SWARMIT_VOLUMES_PATH: "${VOLUMES_FOLDER}"
    networks:
      otcbox_core:
      otcbox_public:
      otcbox_swarmit_core_logs_dozzle:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_FOLDER}/volumes/otcbox/swarmit/hooks:/var/lib/swarmit/hooks
      - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime:ro
      - ${VOLUMES_FOLDER}/volumes/otcbox/swarmit/core/logs/data:/data
    logging:
      driver: json-file
      options:
        max-size: 40m
        max-file: 2
        mode: non-blocking
        max-buffer-size: 4m
networks:
  otcbox_core:
    external: true
  otcbox_public:
    external: true
  otcbox_swarmit_core_logs_dozzle:
    external: true